import NavBarComponent from "./Navbar";
import Headingponent from "./Heading";
import SubHeadingComponent from "./SubHeading";
import ImageComponent from "./Imge";
import ExpressInstallationComponent from "./ExpressInstallation";
import MarketingAutomationComponent from "./MarketingAutomation";
import MarketingAutomationItemComponent from "./MarketingAutomationItem";
import FacebookChatItemComponent from "./FacebookChatItem";
import FacebookChatComponent from "./FacebookChat";
import RevolutionSliderComponent from "./RevolutiionSlider";
import LookBookComponent from "./Lookbook";
import ProductDetailsItemComponent from "./ProductDetailsItem";
import ProductDetailsComponent from "./ProductDetails";
import CheckOutComponent from "./CheckOut";
import NotificationComponent from "./Notification";
import OrderProductComponent from "./OrderProduct";
import ProductPageLayoutComponent from "./ProductPageLayout";
import CustomHeaderComponent from "./CustomHeader";
import ProductImageComponent from "./ProductImage";
import VariantSwatchesComponent from "./VariantSwatches";
import MegaMenuComponent from "./MegaMenu";
import FixedMenuComponent from "./FixedMenu";
import StarAlltimeComponent from "./StarAlltime";

export const NavBar = NavBarComponent;
export const Heading = Headingponent;
export const SubHeading = SubHeadingComponent;
export const Image = ImageComponent;
export const ExpressInstallation = ExpressInstallationComponent;
export const MarketingAutomation = MarketingAutomationComponent;
export const MarketingAutomationItem = MarketingAutomationItemComponent;
export const FacebookChatItem = FacebookChatItemComponent;
export const FacebookChat = FacebookChatComponent;
export const RevolutionSlider = RevolutionSliderComponent;
export const LookBook = LookBookComponent;
export const ProductDetailsItem = ProductDetailsItemComponent;
export const ProductDetails = ProductDetailsComponent;
export const CheckOut = CheckOutComponent;
export const Notification = NotificationComponent;
export const OrderProduct = OrderProductComponent;
export const ProductPageLayout = ProductPageLayoutComponent;
export const CustomHeader = CustomHeaderComponent;
export const ProductImage = ProductImageComponent;
export const VariantSwatches = VariantSwatchesComponent;
export const MegaMenu = MegaMenuComponent;
export const FixedMenu = FixedMenuComponent;
export const StarAlltime = StarAlltimeComponent;
